<a href="https://colab.research.google.com/github/mtryptnkr-study/Fake-News-Prediction/blob/main/P4_FakeNewsPredictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fake News Predictor - Textual Data

- 1: Fake news
- 0: Real news

# Dataset Source
- https://www.kaggle.com/datasets/rahulogoel/isot-fake-news-dataset

# Methodology
1. Data Collection
2. Data pre-preocessing
3. Train-test split
4. Logistic Regression - Binary Classification
5. Evaluation of model on the basis of new data

# Importing Dependencies

In [76]:
import numpy as np
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

- ```re``` - for searching text in document
- ```nltk.corpus``` - Natural Language Toolkit
- ```stopwords``` - words which do not value to the context of data (a, the, and)
- ```TfidfVectorizer``` - convert the text into feature vectors
- ```PorterStemmer``` - Stemming procedure

## Stopwords in English

In [77]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [78]:
print(stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

# Data Pre-processing

In [79]:
fake_data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Machine Learning Projects/P4_Fake News Prediction/Dataset/Fake.csv')
true_data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Machine Learning Projects/P4_Fake News Prediction/Dataset/True.csv')

In [80]:
fake_data.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

## Combining and shuffling the dataset

In [81]:
fake_data['label'] = 1
true_data['label'] = 0

In [82]:
fake_data.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",1
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",1
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",1
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",1
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",1

In [83]:
# Combine the datasets
combined_df = pd.concat([fake_data, true_data], ignore_index=True)

# Shuffle the records randomly
# frac=1 shuffles 100% of the rows
data = combined_df.sample(frac=1, random_state=42).reset_index(drop=True)

In [84]:
data.head()

,title,text,subject,date,label
0,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",US_News,"February 13, 2017",1
1,Trump drops Steve Bannon from National Securit...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"April 5, 2017",0
2,Puerto Rico expects U.S. to lift Jones Act shi...,(Reuters) - Puerto Rico Governor Ricardo Rosse...,politicsNews,"September 27, 2017",0
3,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",News,"May 22, 2017",1
4,Donald Trump heads for Scotland to reopen a go...,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",politicsNews,"June 24, 2016",0

In [85]:
data.shape

(44898, 5)

In [86]:
fake_data.shape

(23481, 5)

In [87]:
true_data.shape

(21417, 5)

## Checking missing values

In [88]:
print(data.isnull().sum())

title      0
text       0
subject    0
date       0
label      0
dtype: int64

## Using the ```title``` and ```text``` for prediction

In [89]:
# merging the title and text
data['content'] = data['title'] + ' ' + data['text']

In [90]:
print(data['content'])

0        Ben Stein Calls Out 9th Circuit Court: Committ...
1        Trump drops Steve Bannon from National Securit...
2        Puerto Rico expects U.S. to lift Jones Act shi...
3         OOPS: Trump Just Accidentally Confirmed He Le...
4        Donald Trump heads for Scotland to reopen a go...
                               ...
44893    UNREAL! CBS’S TED KOPPEL Tells Sean Hannity He...
44894    PM May seeks to ease Japan's Brexit fears duri...
44895    Merkel: Difficult German coalition talks can r...
44896     Trump Stole An Idea From North Korean Propaga...
44897    BREAKING: HILLARY CLINTON’S STATE DEPARTMENT G...
Name: content, Length: 44898, dtype: object

In [91]:
# separating the data & label
X = data.drop(columns='label', axis=1)
y = data['label']

In [92]:
X.head()

,title,text,subject,date,content
0,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",US_News,"February 13, 2017",Ben Stein Calls Out 9th Circuit Court: Committ...
1,Trump drops Steve Bannon from National Securit...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"April 5, 2017",Trump drops Steve Bannon from National Securit...
2,Puerto Rico expects U.S. to lift Jones Act shi...,(Reuters) - Puerto Rico Governor Ricardo Rosse...,politicsNews,"September 27, 2017",Puerto Rico expects U.S. to lift Jones Act shi...
3,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",News,"May 22, 2017",OOPS: Trump Just Accidentally Confirmed He Le...
4,Donald Trump heads for Scotland to reopen a go...,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",politicsNews,"June 24, 2016",Donald Trump heads for Scotland to reopen a go...

In [93]:
y.head()

0    1
1    0
2    0
3    1
4    0
Name: label, dtype: int64

# Stemming Procedure
- Stemming is the process of reducing a word to its root word.
- Removes prefix and suffix.
  - Actor, Actress, Acting --> act is the root word

In [94]:
port_stem = PorterStemmer()

In [95]:
def stemming(content):
  stemmed_content = re.sub('[^a-zA-Z]', ' ', content)
  stemmed_content = stemmed_content.lower()
  stemmed_content = stemmed_content.split()
  stemmed_content = [port_stem.stem(word) for word in stemmed_content if not word in stopwords.words('english')]
  stemmed_content = ' '.join(stemmed_content)
  return stemmed_content

- We are creating a function called ```stemming```.
- We are calling regular expression library to search for text.
- ```sub``` substitutes certain values
- ```[^a-zA-Z]``` considers only the alphabets and removes numbers, punctuations etc. and replaces them by ' '
- We then convert all the alphabets to lower case
- Then we split it in list
- Then we take each word and reduce it to root word while removing the stopwords, so we use ```for``` loop to parse through
- After this we joined the words and return our stemmed content

In [96]:
data['content'] = data['content'].apply(stemming)

In [97]:
print(data['content'])

0        ben stein call th circuit court commit coup ta...
1        trump drop steve bannon nation secur council w...
2        puerto rico expect u lift jone act ship restri...
3        oop trump accident confirm leak isra intellig ...
4        donald trump head scotland reopen golf resort ...
                               ...
44893    unreal cb ted koppel tell sean hanniti bad ame...
44894    pm may seek eas japan brexit fear trade visit ...
44895    merkel difficult german coalit talk reach deal...
44896    trump stole idea north korean propaganda parod...
44897    break hillari clinton state depart gave russia...
Name: content, Length: 44898, dtype: object

# Splitting the data

In [98]:
# separating the data and label
X = data['content'].values
y = data['label'].values

In [99]:
print(X)

['ben stein call th circuit court commit coup tat constitut st centuri wire say ben stein reput professor pepperdin univers also hollywood fame appear tv show film ferri bueller day made provoc statement judg jeanin pirro show recent discuss halt impos presid trump execut order travel stein refer judgement th circuit court washington state coup tat execut branch constitut stein went call judg seattl polit puppet judiciari polit pawn watch interview complet statement note stark contrast rhetor leftist media pundit neglect note court ever block presidenti order immigr past discuss legal efficaci halt actual text execut order read trump news st centuri wire trump filessupport work subscrib becom member wire tv'
 'trump drop steve bannon nation secur council washington reuter u presid donald trump remov chief strategist steve bannon nation secur council wednesday revers controversi decis earli year give polit advis unpreced role secur discuss trump overhaul nsc confirm white hous offici also elev gener joseph dunford chairman joint chief staff dan coat director nation intellig head u intellig agenc offici said chang move nsc back core function suppos also appear mark victori nation secur advis h r mcmaster told nation secur expert felt battl death bannon other white hous staff vice presid mike penc said bannon would continu play import role polici play shake routin natur evolut ensur nation secur council organ way best serv presid resolv make difficult decis penc said fox news bannon said statement succeed return nsc back tradit role coordin foreign polici rather run cite presid barack obama nation secur advis susan rice advoc chang susan rice operation nsc last administr put nsc ensur de operation gener mcmaster nsc back proper function said trump white hous team grappl infight intrigu hobbl young presid recent day sever senior u foreign polici nation secur offici said mechan shape trump administr respons press challeng syria north korea iran still place critic bannon role nsc said gave much weight decis make someon lack foreign polici expertis bannon chief execut trump presidenti campaign month lead elect novemb respect repres trump america first nationalist voic help fuel anti washington fervor push presid part way time mainstream republican join trump administr bannon head breitbart news right wing websit u repres adam schiff rank democrat hous repres intellig committe call shift nsc posit step help mcmaster gain control bodi politic bannon involv administr polici north korea china russia syria continu drift hope shake bring level strateg vision bodi said bannon remov nsc potenti setback sphere influenc trump white hous voic major decis trump confid said bannon remain influenti ever still involv everyth still full confid presid fair much stuff confid said speak condit anonym white hous offici said bannon longer need nsc departur trump first nation secur advis michael flynn flynn forc resign feb contact russia ambassador unit state sergei kislyak prior trump take offic jan offici said bannon place nsc origin check flynn attend one nsc regular meet offici dismiss question power struggl bannon mcmaster say share world view howev two current nation secur offici reject white hous explan note two month pass sinc flynn departur mcmaster said speak condit anonym also duel bannon other direct access trump futur deputi nation secur advis k mcfarland former fox news comment intellig director ezra cohen watnick flynn appointe staf decis trump prepar first face face meet thursday friday chines presid xi jinp threat north korea nuclear missil program key compon talk bannon seat nsc princip committe group includ secretari state defens rank aid taken rick perri energi secretari charg overse u nuclear weapon arsen'
 'puerto rico expect u lift jone act ship restrict reuter puerto rico governor ricardo rossello said wednesday expect feder govern waiv jone act would lift restrict ship provid aid island devast hurrican maria said speak member congress parti support emerg waiver expect waiv rossello said interview cnn note seven day waiver hurrican irma much less devast island tuesday trump administr said need waiv ship restrict help get fuel suppli storm ravag puerto rico say would noth address island damag port main impedi ship waiver would allow puerto rico get help u ship ship bring aid critic particularli fuel said one consider right prioriti get fuel diesel gasolin across island right enough fuel limit transport logist point cours get fuel island go critic major function telecom hospit water run appropri jone act requir good ship u port carri american own oper ship u senat john mccain ask act depart homeland secur secretari elain duke tuesday grant emerg waiver law said puerto rican resid would pay least twice much food drink water suppli without waiver correct version stori fix paragraph four show administr formal deni waiver request'
 ...
 'merkel difficult german coalit talk reach deal berlin reuter chancellor angela merkel said german parti face difficult task bridg differ crunch coalit talk thursday believ reach agreement work togeth new govern differ posit told report work think work posit result end today negoti difficult task'
 'trump stole idea north korean propaganda parodi account push stupid wall detail jesu f cking christ presid moron satisfi simpli wast billion taxpay dollar border wall donald want see preserv view sceneri afraid peopl might kill gigant sack drug total go thrown regular basi thu negat argument wall somehow curb drug traffick horribl sound throw larg sack drug peopl side wall see hit head pound stuff presid said aboard air forc one wednesday accord offici white hous transcript cray sound need transpar wall trump say border wall mexico transpar peopl kill drug courier throw lb bag pic twitter com gxjuhjpx gregori kort gregorykort juli unclear trump actual said cray white hous stenograph made typo idea beleagu mani fli pound sack drug border wall need transpar pretti cray trump could argu number reason transpar see dirti brownish peopl hate come instanc chose dumb one involv throw pound bag heroin foot fenc natur american find hilari bad hombr strong juha juhasaarinen juli imagin acm print side tj shannon tjshannon juli pic twitter com dr lw paul vahamaa pvahamaa juli steel wall open see wall know describ fenc right tinz tinzrul juli likelihood trump heard someon say need transpar build wall understand patrick patrickcragg juli crush giant bag dope pretti high peopl prefer way die list heard dessert love crimedrama juli crush giant bag dope opinion giant bag dope best album david j britton tyburn cross juli want meet dealer toss lb bag wall use catapult nicefellow nicefellow juli prefer trebuchet told carli whatstudentloan juli beauti though bag miss head hey free heroin christoph keelti keeltyc juli area far away border part border far away border wtf cray matthew r kern mattkern juli drug smuggler toss pound bag coke foot wall climb mountain high qualiti nephew johnnephew juli piec fenc would supe far away tote cray cross fo sho need def fleek henkepotamu henk juli laugh seriou problem pic twitter com jgkvdgmt eras rewind eraserewind juli peopl throw lb sack stuff high wall get team rich argonzo juli happen stand next giant mi wall bam hit lb bag drug toss huge wall one spooki comet spookycomet juli one thing right shit cray ella girl ellasgirl juli possibl real never mind sorri forgot refer kit yona thekitastroph juli wow viciou river cray lb fall bag heroin would peopl stand next wall starbuck tom broun tazmpictur juli ask point violent viciou river map wtf talk john daw grajilla juli f ck throw lb sack drug wall caus pretti sure make pro sport r goldman sttrzangel juli would trump get idea tell american crimin across border kill peopl giant sack drug north korean propaganda cours seem like north korean propaganda realiz parodi account six innoc children kill south korean crimin hurl huge sack illeg drug inter korean demilitar zone wall pic twitter com bfnnlbi e dprk news servic dprk news juli think disgrac even trump probabl awar yet seen depth will sink quest power need face fact presid complet cray let gop know need job remov offic featur imag via getti imag screengrab'
 'break hillari clinton state depart gave russia half u uranium reward donor toast bigger troubl thought much whole thing get wors bill hill chicken come home roost hillari clinton state depart part panel approv sale one america largest uranium mine time foundat control seller chairman make donat clinton famili chariti record review wall street journal show million sale uranium one unit rosatom russia state nuclear agenc approv u feder committe assess secur implic foreign invest state depart mr clinton ran one member clinton giustra sustain growth initi project clinton foundat receiv million fernwood foundat famili chariti run ian telfer chairman uranium one sale accord canada revenu agenc record donat first report clinton cash new book peter schweizer editor larg conserv news websit financi deal mr clinton former presid bill clinton copi book set releas next month review wall street journal book publish harpercollin divis news corp also publish journal via breitbart news']

In [100]:
print(y)

[1 0 0 ... 0 1 1]

# Converting the textual data to numerical data
- We need to convert all the text into computer understandable numbers
- ```TfidfVectorizer``` - Term Frequency Function
  - number of times the word is repeating and assigns a value to it

In [101]:
vetorizer = TfidfVectorizer()
vetorizer.fit(X)

X = vetorizer.transform(X)

In [102]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6904081 stored elements and shape (44898, 89868)>
  Coords	Values
  (0, 641)	0.05228664096628702
  (0, 2301)	0.031027142587997773
  (0, 3547)	0.0488071293292804
  (0, 6676)	0.04884347413276789
  (0, 6957)	0.16386262721973816
  (0, 8254)	0.06315631043962108
  (0, 9342)	0.08630781517552194
  (0, 10207)	0.17073096196903942
  (0, 11021)	0.0668114796652417
  (0, 12311)	0.13322555039706324
  (0, 13703)	0.17834547765750505
  (0, 14832)	0.058143818186916094
  (0, 14922)	0.05674091538137144
  (0, 15293)	0.12427662090796918
  (0, 15379)	0.08367337417927549
  (0, 15857)	0.1738925675982146
  (0, 15874)	0.1510751930350872
  (0, 17608)	0.03800104523939401
  (0, 19389)	0.10424208397556521
  (0, 21714)	0.14586212082964276
  (0, 23524)	0.05444062170305505
  (0, 23719)	0.16347523092935848
  (0, 24305)	0.10158376192651036
  (0, 24994)	0.12248771532966563
  (0, 25243)	0.08802206365616412
  :	:
  (44897, 66432)	0.11456982900715149
  (44897, 67014)	0.04069543847176415
  (44897, 67086)	0.092110829911283
  (44897, 67673)	0.20199884744457217
  (44897, 68850)	0.11423176584775005
  (44897, 69285)	0.03678856096715407
  (44897, 69465)	0.10461136864376028
  (44897, 69785)	0.04414132352634072
  (44897, 70799)	0.034605908359915935
  (44897, 73662)	0.098097127178316
  (44897, 74353)	0.10344952880150131
  (44897, 75218)	0.07672792468712465
  (44897, 76695)	0.13839362723854398
  (44897, 77540)	0.03891287143949881
  (44897, 77657)	0.051763600043088276
  (44897, 77960)	0.028151431327364702
  (44897, 78362)	0.10874450312964964
  (44897, 79480)	0.06377633149488104
  (44897, 81621)	0.03230323170235401
  (44897, 82221)	0.37338365919122324
  (44897, 83348)	0.033647709732464094
  (44897, 84467)	0.10767565066212043
  (44897, 85031)	0.05774314291543106
  (44897, 85670)	0.05833837111916366
  (44897, 86615)	0.06115026854427637

# Splitting for training the model

In [103]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

# Predicting using Logistic Regression

In [104]:
model = LogisticRegression()

In [105]:
model.fit(X_train, y_train)

LogisticRegression()

## Evaluation

In [106]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, y_train)
print('Accuracy Score of training data: ', training_data_accuracy)

Accuracy Score of training data:  0.9911465003619355

In [107]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, y_test)
print('Accuracy Score of test data: ', test_data_accuracy)

Accuracy Score of test data:  0.9857461024498887

# Predicting using RF Classifier

In [108]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [110]:
model2 = RandomForestClassifier(n_estimators=100, random_state=42)
model2.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

## Evaluation

In [111]:
# accuracy on training data
X_train_prediction_RF = model2.predict(X_train)
training_data_accuracy_RF = accuracy_score(X_train_prediction_RF, y_train)
print('Accuracy Score of training data: ', training_data_accuracy_RF)

Accuracy Score of training data:  1.0

In [112]:
# accuracy on test data
X_test_prediction_RF = model2.predict(X_test)
test_data_accuracy_RF = accuracy_score(X_test_prediction_RF, y_test)
print('Accuracy Score of test data: ', test_data_accuracy_RF)

Accuracy Score of test data:  0.9934298440979955

In [113]:
print(classification_report(y_test, X_test_prediction_RF))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      4284
           1       1.00      0.99      0.99      4696

    accuracy                           0.99      8980
   macro avg       0.99      0.99      0.99      8980
weighted avg       0.99      0.99      0.99      8980

In [114]:
cm = confusion_matrix(y_test, X_test_prediction_RF)
print(cm)

[[4263   21]
 [  38 4658]]

# Making a Predictive System of the best model

In [115]:
X_new = X_test[0]

prediction = model2.predict(X_new)
print(prediction)

if prediction[0]==0:
  print('The news is Real')
else:
  print('The news is Fake')

[1]
The news is Fake

In [116]:
print(y_test[0])

1